### ISSUE TITLE
有最新的版本么？

### ISSUE THREAD

**Issue by flyfish0612** [alibaba/FlexGW#4]
我看到评论你们说修复了2.4的bug,这里怎么都没有更新了呀。

**Comment by r4ntix** [comment]
你好，请问是在哪里看到的评论？基于本仓库生成的FlexGW 目前还没有收到Bug 反馈。

**Comment by flyfish0612** [comment]
https://market.aliyun.com/products/56812015/cmjj006981.html?spm=5176.730005.0.0.2f1Kk7
云市场里面回复的。
